### ISSUE TITLE
Missing types

### ISSUE THREAD

**Issue by EHadoux** [lume/kiwi#4]
Hey, it looks like the new version doesn't ship the types. 

```
Could not find a declaration file for module '@lume/kiwi'. '...../node_modules/@lume/kiwi/dist/kiwi.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/lume__kiwi` if it exists or add a new declaration (.d.ts) file containing `declare module '@lume/kiwi';`
```

```json
"main": "dist/kiwi.js",
"types": "dist/kiwi.d.ts",
```

![image](https://github.com/lume/kiwi/assets/1655646/ae2e6733-e581-45c0-86c9-209b8ca0c9b9)

**Comment by trusktr** [comment]
Whoops, thanks! I noticed this too just now testing dependent packages. Fixed in 3eb49a110783641e6a22bd75a6293585e846a91f (forgot to update the `files` array), released in 0.4.1.
